sudo: required
services:
  - docker

before-install:
  - docker build -t prageethn/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true prageethn/react-test npm test

after_success:
  - docker build -t prageethn/multi-client ./client
  - docker build -t prageethn/multi-nginx ./nginx
  - docker build -t prageethn/multi-server ./server
  - docker build -t prageethn/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push prageethn/multi-client
  - docker push prageethn/multi-nginx
  - docker push prageethn/multi-server
  - docker push prageethn/multi-worker
   